services:
  - type: web
    runtime: python
    name: obsidian-source-note-api
    plan: free
    buildCommand: pip install -r requirements-remote.txt
    startCommand: gunicorn app:app
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: "3.11"
